[project]
name = "pet-travel"
version = "0.3.0"
[tool.semantic_release]
version_variables = ["app/__init__.py:__version__", "pyproject.toml:version"]
branch = "main"
upload_to_pypi = false
commit_version_number = true
tag_format = "v{version}"
changelog_file = "CHANGELOG.md"