[semantic_release]
version_variable = "app/__init__.py:__version__"
branch = "main"
upload_to_pypi = false
commit_version_number = true
tag_format = "v{version}"
changelog_file = "CHANGELOG.md"
